resources:
  - ../../base
  - namespace.yaml
  - storage.yaml
namespace: blog-production
commonLabels:
  environment: production
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: blog
  path: blog-deploy-change-env.yaml
images:
  - name: docker.io/ACCOUNT/IMAGE
    newName: lingxiankong/blog-demo
    newTag: 1.1.0
