---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  type: b1.standard
  availability: nz-hlz-1a
  fstype: ext4
