---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: docker.io/ACCOUNT/IMAGE:TAG
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: DB_CONNECTION
          value: "mysql+pymysql://mysql-0.mysql.blog-demo/blog?charset=utf8"
        - name: FLASK_ENV
          value: development
        ports:
          - name: blog
            containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: blog
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
    - name: blog
      protocol: TCP
      port: 5000
      targetPort: blog
